# Generated by Django 3.0.3 on 2020-04-27 05:39

import apps.miembro.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=70)),
                ('codigo_postal', models.CharField(max_length=5, validators=[apps.miembro.models.valida_codigo_postal])),
                ('localidad', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dni', models.CharField(blank=True, max_length=18)),
                ('fecha_nacimiento', models.DateField()),
                ('nik_od', models.CharField(max_length=20)),
                ('fecha_inscripcion', models.DateField()),
                ('tipo_miembro', models.CharField(choices=[('F', 'Fundador'), ('H', 'Socio de honor'), ('P', 'Presidente de honor'), ('-', 'General')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cobro', models.DateField()),
                ('tipo_cobro', models.CharField(choices=[('S', 'Socio'), ('D', 'Donativo'), ('C', 'Colaborador')], max_length=1)),
                ('importe', models.DecimalField(decimal_places=2, default='-', max_digits=5)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miembro.Miembro')),
            ],
        ),
    ]
