# Generated by Django 3.0.3 on 2020-04-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='tipo_miembro',
            field=models.CharField(choices=[('F', 'Fundador'), ('H', 'Socio de honor'), ('P', 'Presidente de honor'), ('G', 'General')], max_length=1),
        ),
    ]
