# Generated by Django 3.0.3 on 2020-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0003_auto_20200429_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
