# Generated by Django 3.0.3 on 2020-05-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=50)),
                ('fecha_pago', models.DateField()),
                ('tipo_pago', models.CharField(choices=[('S', 'Servidor')], max_length=1)),
                ('importe', models.DecimalField(decimal_places=2, default='-', max_digits=5)),
            ],
        ),
    ]
