# Generated by Django 3.0.3 on 2020-05-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='tipo_pago',
            field=models.CharField(choices=[('S', 'Servidor'), ('C', 'Comisiones')], max_length=1),
        ),
    ]
